LOSS = "mse"
OPTIMIZER = "adam"
VALIDATION_SPLIT = 0.2
PREDICTION_SPLIT = 0.01
NN_HIDDEN_LAYERS = (32, 64, 32)
INJECTION_LAYERS = {1: (1, )}
ACTIVATION = 'relu'


"""
Structure of data
"""
DATA_NUM_VARIABLES = 3
SLIDING_WINDOW_LENGTH = 5
