LOSS = "mse"
OPTIMIZER = "adam"
VALIDATION_SPLIT = 0.25
NN_HIDDEN_LAYERS = (64, 124, 64)
INJECTION_LAYERS = {1: (1, )}
PREDICTION_TIME_STEP = 0.5


"""
Structure of data
"""
DATA_NUM_VARIABLES = 3
SLIDING_WINDOW_LENGTH = 5
